### ISSUE TITLE
Code review for map-state management implemnetation

### ISSUE THREAD

**Issue by sean-olson-esri** [sean-olson-esri/2018_dev_summit_arcgis_api_angular_cli#1]
Hi @andygup  / @jwasilgeo, I implemented a very simple state management example and committed it to its own branch.  If you have a chance, I could any feedback you might have.  I was thinking of doing two examples on map-state management: a simple one to demonstrate the concept and a more complex one to show the possibilities. --Sean

**Comment by andygup** [comment]
Looking good! A few suggestions:

* For future reviews I recommend using the [Github review](https://help.github.com/articles/about-pull-request-reviews/) functionality. Create a pull request for your working branch and then initiate the review that way we can write comments inline -- easy peasy.  Or, simply do a pull request and we can comment in-line without an official review.
* We probably want all the samples under a samples directory. For example, we could rename `/code_snippets` to something like `/samples` and name subdirectories with description names. 
* Should we keep each `/samples/subdirectory` as it's own self-contained, angular app? Seems like that would help keep it simple, and allow us to isolate each sample with its own tests. Not sure how others example repos do this?
* Use arrow functions to maintain function scope rather than using `const self = this;`
https://github.com/sean-olson-esri/2018_dev_summit_arcgis_api_angular_cli/blob/map_state_management/ng_implmentation/src/app/esri-map/esri-map.component.ts#L57 
* Consider moving [`map-state.service.ts`](https://github.com/sean-olson-esri/2018_dev_summit_arcgis_api_angular_cli/blob/map_state_management/ng_implmentation/src/app/map-state.service.ts) under a `/services` subdirectory. We can copy the same pattern across all samples that we build.

I hope that helps!

**Comment by jwasilgeo** [comment]
@sean-olson-esri thanks for all this and it is a great start to our upcoming collaboration.  Thanks!

@andygup I agree with your comments.  I'll probably have more specific code comments once we have a PR set up.  (Sorry I wasn't able to get to this sooner, away from email recently.)

**Comment by sean-olson-esri** [comment]
Thanks @andygup.  Good suggestions all.  I'll reorganize the repo Friday along the lines you suggest.

**Comment by sean-olson-esri** [comment]
closes #1
